{ pkgs, ... }:

[
  (import ./architectury.nix { inherit pkgs; })
  (import ./athena.nix { inherit pkgs; })
  (import ./bclib.nix { inherit pkgs; })
  (import ./bookshelf-lib.nix { inherit pkgs; })
  (import ./cloth-config.nix { inherit pkgs; })
  (import ./cobweb.nix { inherit pkgs; })
  (import ./coroutil.nix { inherit pkgs; })
  (import ./creativecore.nix { inherit pkgs; })
  (import ./cristel-lib.nix { inherit pkgs; })
  (import ./fabric-api.nix { inherit pkgs; })
  (import ./fabric-language-kotlin.nix { inherit pkgs; })
  (import ./forge-config-api-port.nix { inherit pkgs; })
  (import ./glitchcore.nix { inherit pkgs; })
  (import ./geckolib.nix { inherit pkgs; })
  (import ./jei.nix { inherit pkgs; })
  (import ./kiwi.nix { inherit pkgs; })
  (import ./lithostitched.nix { inherit pkgs; })
  (import ./midnight-lib.nix { inherit pkgs; })
  (import ./moonlight-lib.nix { inherit pkgs; })
  (import ./owo.nix { inherit pkgs; })
  (import ./paxi.nix { inherit pkgs; })
  (import ./patchouli.nix { inherit pkgs; })
  (import ./polymer.nix { inherit pkgs; })
  (import ./prickle.nix { inherit pkgs; })
  (import ./resourceful-lib.nix { inherit pkgs; })
  (import ./surveyor.nix { inherit pkgs; })
  (import ./world-weaver.nix { inherit pkgs; })
  (import ./yungs-api.nix { inherit pkgs; })
]
